version: "3.7"

services:
  fastapi-app:
    build:
      context: ./todo_app     # Dockerfile 위치
      dockerfile: Dockerfile  # (기본값이 ‘Dockerfile’이라 생략 가능)
    container_name: fastapi-app     # 관례상 소문자·하이픈
    ports:
      - "5001:5001"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"   # Map 형식이 권장
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
